baseURL = "Https://blog.fromkk.com"
languageCode = "en"
title = "KK's Blog"
theme = "hugo-coder"
enableRobotsTXT = true

paginate=20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Disqus Username
disqusShortname = "kkblog-1"

# Google Analytics UA number
googleAnalytics = "UA-153788833-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[params]
    author = "KK"
    info = "~ Happy Coding ~"
    description = "KK's personal websites"
    keywords = "blog,developer,personal,python,golang,linux,machine learning"
    avatarurl = "images/avatar.png"

    favicon_32 = "/icons/icon-32x32.png"
    favicon_16 = "/icons/icon-16x16.png"

    custom_css = ["css/custom.css"]

    dateformat = "01/02/2006"

    hidecredits = false
    hidecopyright = false

    rtl = false
    katex  = true

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/2251785/hunger"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 3
    url = "bebound # gmail.com"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss fa-2x"
    weight = 4
    url = "/post/index.xml"



[[menu.main]]
  name = "Blog"
  weight = 1
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = 2
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = 3
  url = "/about/"

